name: super-Linter

on: push

jobs:
  super-lint:
  name: lint code base
  runs-on: ubuntu-latest
  steps:
    -name: checkout code
     uses: actions/checkout@v2

     -name: Run super-linter
      uses: github/super-linter@v3
      env:
        DEFAULT BRANCH: main
        GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}
